graphql-java/java-dataloader

src/main/java/org/dataloader/impl/PromisedValues.java
src/main/java/org/dataloader/impl/PromisedValuesImpl.java
src/test/java/org/dataloader/impl/PromisedValuesImplTest.java

Better generics

---

README.md
build.gradle
src/main/java/org/dataloader/DataLoaderRegistry.java
src/main/java/org/dataloader/graphql/DataLoaderDispatcherInstrumentation.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/graphql/DataLoaderDispatcherInstrumentationTest.java

Now has graphql support so users of this library can plug directly into graphql-java more easily
See #3

3 instrumentation dispatcher

---

src/main/java/org/dataloader/DataLoader.java

Changed the locking behavior to be the same throughout the method.

Locking behavior conditional to caching being enabled

---

src/main/java/org/dataloader/DataLoader.java
src/test/java/org/dataloader/DataLoaderTest.java

Fix dispatch hanging when load() is called twice with the same key

---

src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/DataLoaderOptions.java
src/test/java/org/dataloader/DataLoaderTest.java

This is off by default but for long lived caches it makes sense

Added an option to stop the caching of exceptional values

---

.travis.yml
src/main/java/org/dataloader/DataLoaderRegistry.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java

I use `java-dataloader` in coordination of `graphql-java`. I'm running into a use case where I need to lazily construct and register data loaders only if they don't exist already in the registry. 
Currently, there is no exposed way to perform this action atomically through the `DataLoaderRegistry` since it rightfully encapsulates its concurrent hash map.
This PR exposes this capability. 
unit tests covering the new method. 
Note: Any thoughts about adding Spock to the mix later?

Ability to atomically compute a data loader if absent

---

src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/impl/CompletableFutureKit.java
src/test/java/org/dataloader/DataLoaderIfPresentTest.java

This is not finished - this was  a quick POC and tests

getIfPresent and getIfCompleted support

---

src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/DataLoaderRegistry.java
src/test/java/org/dataloader/DataLoaderTest.java

For context: I'm working on a change to allow better composability of `DataLoader`s.  Right now, you can't nest `DataLoader.load().thenApply()` within another similar call.  When a GraphQL field resolution expects a result type `V`, you can return a `CompletableFuture<T>` (e.g. due to a `DataLoader`), but you *can't* return a `CompletableFuture<CompletableFuture<T>>` and so on.  So, instead of being able to chain `DataLoader`s together, you have to come up with a specialized `DataLoader` to calculate the one specific field you want.  I'm trying to make it so that you *can* chain `DataLoader`s together.
The bulk of the change is going to be in `graphql-java`, in another PR.  But that change is going to need insight into what happened when a `dispatchAll` was done in the …

Allow dispatch() caller to get stats back.

---

build.gradle
gradle/publishing.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/org/dataloader/BatchLoader.java
src/main/java/org/dataloader/BatchLoaderContextProvider.java
src/main/java/org/dataloader/BatchLoaderEnvironment.java
src/main/java/org/dataloader/BatchLoaderEnvironmentProvider.java
src/main/java/org/dataloader/BatchLoaderWithContext.java
src/main/java/org/dataloader/CacheMap.java
src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/DataLoaderOptions.java
src/main/java/org/dataloader/DataLoaderRegistry.java
src/main/java/org/dataloader/DispatchResult.java
src/main/java/org/dataloader/Internal.java
src/main/java/org/dataloader/PublicApi.java
src/main/java/org/dataloader/PublicSpi.java
src/main/java/org/dataloader/Try.java
src/main/java/org/dataloader/impl/Assertions.java
src/main/java/org/dataloader/impl/CompletableFutureKit.java
src/main/java/org/dataloader/impl/DefaultCacheMap.java
src/main/java/org/dataloader/impl/PromisedValues.java
src/main/java/org/dataloader/impl/PromisedValuesImpl.java
src/main/java/org/dataloader/stats/Statistics.java
src/main/java/org/dataloader/stats/StatisticsCollector.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java
src/test/java/org/dataloader/DataLoaderTest.java

The PR 56 followup work

---

src/main/java/org/dataloader/BatchLoaderEnvironment.java
src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/impl/CompletableFutureKit.java
src/main/java/org/dataloader/impl/DefaultCacheMap.java
src/main/java/org/dataloader/impl/PromisedValuesImpl.java

Hello,
thank you for this nice library. I would like to propose few minor fixes:
- missing Thread.currentThread().interrupt(); after catching InterruptedException
- converting Object.nonNull to Assertions.nonNull
- removing some vestigial @SuppressWarnings("unchecked")

minor code cleanups

---

src/main/java/org/dataloader/CacheKey.java
src/main/java/org/dataloader/DataLoaderHelper.java

When result depends on both key and context, i.e. `load(key, context)`, cacheKey should depend on context.

Generate cache key with loadContext.

---

src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/annotations/VisibleForTesting.java
src/test/java/org/dataloader/DataLoaderTimeTest.java

Related in a way to #77 - without the threading
I think it will be useful to have a last dispatched instant

Added a instant since last dispatch value

---

README.md
src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderFactory.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/DataLoaderRegistry.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/DataLoaderBatchLoaderEnvironmentTest.java
src/test/java/org/dataloader/DataLoaderIfPresentTest.java
src/test/java/org/dataloader/DataLoaderMapBatchLoaderTest.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java
src/test/java/org/dataloader/DataLoaderStatsTest.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/DataLoaderTimeTest.java
src/test/java/org/dataloader/DataLoaderWithTryTest.java

Rather than have all of the methods on the DataLoader class, we now have a factory
Also created a builder for DataLoaderRegistry
We should have always had that instead of a mutable class

Introduces a Factory for creating DataLoaders

---

README.md
src/main/java/org/dataloader/DataLoaderRegistry.java
src/main/java/org/dataloader/annotations/ExperimentalApi.java
src/main/java/org/dataloader/registries/DispatchPredicate.java
src/main/java/org/dataloader/registries/ScheduledDataLoaderRegistry.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/ClockDataLoader.java
src/test/java/org/dataloader/fixtures/TestKit.java
src/test/java/org/dataloader/registries/DispatchPredicateTest.java
src/test/java/org/dataloader/registries/ScheduledDataLoaderRegistryTest.java

A DataLoaderRegistry that will evaluate a predicate before actually calling dispatch on the dataloaders within
if they return false, then it reschedules the dispatch call for another time (schedule duration) and trys again.
This PR was inspired by the work in #77 - the difference is the threading is outside the DL classes and it has a flexible predicate on when to dispatch, allowing people to write custom logic here

Adding a ScheduledDataLoaderRegistry

---

src/main/java/org/dataloader/DataLoaderHelper.java

**Describe the bug**
A bug that may cause jobs not to be added to `loaderQueue` due to race conditions.
`DataLoader.load(K key, Object loadContext)`  has two ways of getting value, first - get immediately or add to queue, second - retrieve from the cache. Retrieving from cache works through consecutive CompletableFuture calls, if the cache misses then we add to queue or load immediately. The first way covered by synchronized on `dataLoader` but the second isn't.
This PR fixes this issue by adding synchronized on callback if the cache misses
**To Reproduce**
It's hard to reproduce because of multithreading

Add synchronized to loaderQueue inside completable future

---

README.md
build.gradle
src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/DataLoaderOptions.java
src/main/java/org/dataloader/Try.java
src/main/java/org/dataloader/ValueCache.java
src/main/java/org/dataloader/ValueCacheOptions.java
src/main/java/org/dataloader/impl/Assertions.java
src/main/java/org/dataloader/impl/DataLoaderAssertionException.java
src/main/java/org/dataloader/impl/PromisedValuesImpl.java
src/test/java/org/dataloader/DataLoaderValueCacheTest.java
src/test/java/org/dataloader/TryTest.java
src/test/java/org/dataloader/fixtures/CustomValueCache.java
src/test/java/org/dataloader/fixtures/TestKit.java

The ValueCache is an async affair.
The previous PRs such as https://github.com/graphql-java/java-dataloader/pull/91 handled it badly because they made the "load" call asynchronous with repect to the method returning a CF that might need to be dispatched
This fixes this by approaching it differently.
The BatchLoader is an async method and hence we can call the ValueCache then, meaning given 10 keys, if it gets 6 from the cache first it need only batch call for 4 after wards.
The results are then combined together again.
This opens another possibility - that is being able to do "batch cache" lookups.  This has been added to ValueCache and if the implementation cant do batch lookup it just delegates back to the singleton `get` calls.
For something backed by say REDIS (which can do batch …

ValueCache calls are made inside the batch load call

---

src/main/java/org/dataloader/DataLoader.java
src/test/java/org/dataloader/DataLoaderTest.java

This change allows for priming loaders with async results, which is
useful when the underlying source of values is itself async/reactive.

Allow priming with future values

---

src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/annotations/GuardedBy.java

As `@GuardedBy("dataLoader") ` describe, the thread is already hold `dataLoader ` lock when `loadFromCache`  is called.
https://github.com/graphql-java/java-dataloader/blob/4253050b302c6e342a42a67bdab094844ba643ff/src/main/java/org/dataloader/DataLoaderHelper.java#L102

Add @GuardedBy and remove redundant synchronized

---

src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/ValueCache.java
src/main/java/org/dataloader/impl/NoOpValueCache.java

The original PR : https://github.com/graphql-java/java-dataloader/pull/108 shows we are allocating too many objects.
This takes it further by introducing a fast exception to allow a `ValueCache` to short circuit out of a look up.
This is then used by the default NoopValueCache and hences saves memory and processing for every one  NOT using a ValueCache

Short circuit value cache look up to avoid object allocations

---

src/main/java/org/dataloader/DataLoaderOptions.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java
src/test/java/org/dataloader/DataLoaderStatsTest.java

We rarely need statistics info from dataLoader, and it would be better to make NoOpStatisticsCollector default, just like guava cache.

Make NoOpStatisticsCollector to be default StatisticsCollector

---

src/main/java/org/dataloader/CacheMap.java
src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/impl/DefaultCacheMap.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/DataLoaderCacheMapTest.java
src/test/java/org/dataloader/DataLoaderIfPresentTest.java
src/test/java/org/dataloader/fixtures/CustomCacheMap.java

in an attempt so write a better `Instrumentation` that could dispatch a `DataLoaderRegistry` in a more optimized way [we created a custom Instrumentation](https://opensource.expediagroup.com/graphql-kotlin/docs/server/data-loader/data-loader-instrumentation#dispatching-by-synchronous-execution-exhaustion) that tracks the state of each `ExecutionStrategy` of an `ExecutionInput` and dispatch the DataLoaderRegistry when no more synchronous code could be executed.
more information
https://github.com/graphql-java/graphql-java/discussions/2715
this PR adds a method to the `DataLoader` class that provides a read-only list of CacheMaps associated with the DataLoader, this will help to keep track of the `numberOfDependents` of each future.
by doing this we would also be solving a problem …

feat: make cache map values accesible for read only purposes

---

build.gradle

Fixes #110 
[graphql-java](https://github.com/graphql-java/graphql-java) has the Automatic Module Name `com.graphqljava`, and it also directly depends on java-dataloader. Since java-dataloader also has the Automatic Module Name `com.graphqljava`, the module system cannot determine which module to use and so any usage of graphql-java with the module path is instantly broken.
This patch changes the Automatic Module Name to `org.dataloader` since that's the root package name.
Given that:
- Automatic Module Name is only relevant when using the module path
- java-dataloader is inherently always used with graphql-java, and so in its current state on the module path is completely broken
then I believe this is a passive change - not sure what the release process is around bumping versions since …

Changed Automatic Module Name to org.dataloader

---

src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/stats/DelegatingStatisticsCollector.java
src/main/java/org/dataloader/stats/NoOpStatisticsCollector.java
src/main/java/org/dataloader/stats/SimpleStatisticsCollector.java
src/main/java/org/dataloader/stats/StatisticsCollector.java
src/main/java/org/dataloader/stats/ThreadLocalStatisticsCollector.java
src/main/java/org/dataloader/stats/context/IncrementBatchLoadCountByStatisticsContext.java
src/main/java/org/dataloader/stats/context/IncrementBatchLoadExceptionCountStatisticsContext.java
src/main/java/org/dataloader/stats/context/IncrementCacheHitCountStatisticsContext.java
src/main/java/org/dataloader/stats/context/IncrementLoadCountStatisticsContext.java
src/main/java/org/dataloader/stats/context/IncrementLoadErrorCountStatisticsContext.java
src/test/java/org/dataloader/DataLoaderStatsTest.java
src/test/java/org/dataloader/stats/StatisticsCollectorTest.java

The `StatisticsCollector` interface is useful for gathering basic
metrics about data loaders, but is limited in that we are unable to pass
in any sort of context (key or call). This would allow us to obtain more
insightful metrics (for example, we would be able to break down metrics
based on the GraphQL operation name).
To this end, we add `*StatisticsContext` objects to each
`StatisticsCollector` method; we provide distinct implementations for
each one rather than a generic catch-all so that we may evolve them
independently as needed.

Add context objects to StatisticsCollector methods

---

src/main/java/org/dataloader/DataLoaderOptions.java

This looks like an accidental omission, so we include this along with
all the other variables inside this class.

Copy across valueCache in DataLoaderOptions copy constructor

---

build.gradle

Adding this so build versions do not appear as the "latest" release on Maven, when sorting in descending order

Prepend 0.0.0 to build version

---

README.md
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/DataLoaderOptions.java
src/main/java/org/dataloader/scheduler/BatchLoaderScheduler.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/fixtures/TestKit.java
src/test/java/org/dataloader/scheduler/BatchLoaderSchedulerTest.java

This adds a new callback mechanism that allows the invocation of the batch loader function to be done some time in the future.
This capability was in the original JS reference implementation but never implemented in this port.
if no `BatchLoaderScheduler` is provided (its null) then it will be invoked immediately as before

Batch scheduler function support

---

src/main/java/org/dataloader/DataLoaderRegistry.java
src/main/java/org/dataloader/annotations/GuardedBy.java
src/main/java/org/dataloader/registries/DispatchPredicate.java
src/main/java/org/dataloader/registries/ScheduledDataLoaderRegistry.java
src/test/java/org/dataloader/DataLoaderRegistryPredicateTest.java
src/test/java/org/dataloader/fixtures/TestKit.java
src/test/java/org/dataloader/registries/ScheduledDataLoaderRegistryPredicateTest.java

This adds a map of per dataloader predicates to ScheduledDataLoaderRegistry so people can have more fine grain control on when a dataloader is dispatched.
if its not used then it goes back to the default behavior of one predicate for the ScheduledDataLoaderRegistry

Adds a predicate to DataLoaderRegistry and a per dataloader map of pedicates is also possible

---

README.md
src/main/java/org/dataloader/registries/ScheduledDataLoaderRegistry.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/fixtures/TestKit.java
src/test/java/org/dataloader/registries/ScheduledDataLoaderRegistryTest.java

This creates a ticker mode where by calls to the dataloaders will always be rescheduled after the first `.dispatch()` call is made
Read the readme and javadoc in the PR for all gory details

Ticker mode on ScheduledDataLoaderRegistry

---

src/main/java/org/dataloader/registries/ScheduledDataLoaderRegistry.java

Calling ScheduledDataLoaderRegistry.newScheduledRegistry would create a new ScheduledExecutorService on every call, regardless of whether a custom one was supplied. Move creation of the default ScheduledExecutorService from the builder field to the build method to avoid the issue. Fixes #134

Lazily initialize Executor in ScheduledDataLoaderRegistry builder

---

src/main/java/org/dataloader/DataLoaderHelper.java

Bail out early in DataLoaderHelper.dispatch when loaderQueue is empty to avoid unnecessary allocations; additionally, when there is work, size the allocated Lists precisely based on the loaderQueue size. Fixes #132

Avoid allocations in DataLoaderHelper.dispatch when there's no work

---

src/main/java/org/dataloader/registries/ScheduledDataLoaderRegistry.java
src/test/java/org/dataloader/registries/ScheduledDataLoaderRegistryPredicateTest.java

See https://github.com/graphql-java/java-dataloader/issues/138
This changes the dispatcing predicate so that IF a specific predicate is regisestered against a data loader - its answer is final.
The old code defaulted and on reflection thats just janky defaulting

If there is a specific predicate for a dataloader - its is the final say on whether to dispatch

---

src/main/java/org/dataloader/CacheMap.java
src/main/java/org/dataloader/DataLoaderHelper.java

Currently, when accessing values from the `DataLoader`'s `CacheMap`, we first check `#containsKey` before invoking `#get`. This is problematic for two reasons:
- the underlying cache's metrics are skewed (it will have a 100% hit rate).
- if the cache has an automatic expiration policy, it is possible a value will expire between the `containsKey` and `get` invocations leading to an incorrect result.
To ameliorate this, we always invoke `#get` and check if it is `null` to deterine whether the key is present. We wrap the invocation in a `try`/`catch` as the `#get` method is allowed to through per its documentation.

Remove CacheMap#containsKey before #get

---

src/test/java/org/dataloader/DataLoaderTest.java

As a fast follow to #146, we add a regression test to ensure that we still handle a `CacheMap` whose `#get` throws an exception (by falling back to the underlying batch loader).

Verify a throwing CacheMap#get does not break DataLoader

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
build.gradle
src/test/java/org/dataloader/DataLoaderTest.java

`graphql-java` is already on Java 11 so we take the liberty of bumping this library to the same version to unlock some nice features.

Bump to Java 11

---

build.gradle
src/test/java/org/dataloader/DataLoaderBatchLoaderEnvironmentTest.java
src/test/java/org/dataloader/DataLoaderCacheMapTest.java
src/test/java/org/dataloader/DataLoaderIfPresentTest.java
src/test/java/org/dataloader/DataLoaderMapBatchLoaderTest.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java
src/test/java/org/dataloader/DataLoaderStatsTest.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/DataLoaderTimeTest.java
src/test/java/org/dataloader/DataLoaderValueCacheTest.java
src/test/java/org/dataloader/DataLoaderWithTryTest.java
src/test/java/org/dataloader/TryTest.java
src/test/java/org/dataloader/impl/PromisedValuesImplTest.java
src/test/java/org/dataloader/registries/DispatchPredicateTest.java
src/test/java/org/dataloader/registries/ScheduledDataLoaderRegistryPredicateTest.java
src/test/java/org/dataloader/registries/ScheduledDataLoaderRegistryTest.java
src/test/java/org/dataloader/scheduler/BatchLoaderSchedulerTest.java
src/test/java/org/dataloader/stats/StatisticsCollectorTest.java
src/test/java/org/dataloader/stats/StatisticsTest.java

This change is being made to facilitate parameterised tests which should greatly aid in adding coverage for https://github.com/graphql-java/java-dataloader/pull/148.
This was largely powered by the [OpenRewrite recipe](https://docs.openrewrite.org/recipes/java/testing/junit5/junit4to5migration) for JUnit 4.x to Jupiter migration, with a few extra tweaks:
- imports optimised to be single-class (i.e. no `import foo.*;`).
- removed `test_` prefix from legacy JUnit 3 methods.
Notably, this pulls in `org.hamcrest` for `MatcherAssert.assertThat`, which is recommended by both the recipe (which handled this migration) and IntelliJ.

Bump JUnit 4.x to JUnit Jupiter 5

---

.github/workflows/pull_request.yml
src/main/java/org/dataloader/DataLoaderHelper.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/fixtures/TestKit.java
src/test/java/org/dataloader/fixtures/parameterized/ListDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/MappedDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/MappedPublisherDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/PublisherDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/TestReactiveDataLoaderFactory.java

Now working and will complete missing exceptions if we end up short

More tests for Publishers on reactive branch

---

README.md
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/MappedBatchPublisher.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/fixtures/UserManager.java
src/test/java/org/dataloader/fixtures/parameterized/MappedPublisherDataLoaderFactory.java

This is more symmetric with `MappedBatchLoader` and preserves efficiency; we do not need to emit a `Map.Entry` for duplicate keys (given the strong intention that this will be used to create a `Map`).
This was picked up after creating `README` examples, which have also been added here.

Have MappedBatchPublisher take in a Set<K> keys (and add README sections)

---

src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/impl/CompletableFutureKit.java
src/test/java/org/dataloader/DataLoaderBatchLoaderEnvironmentTest.java
src/test/java/org/dataloader/DataLoaderStatsTest.java
src/test/java/org/dataloader/DataLoaderTest.java

Add support for `Map<K, V> loadMany(Map<K, ?> keysAndContexts);` in `DataLoader`.

Add support for batch loading of a Map of key-value pairs.

---

.github/workflows/stale-pr-issue.yml

Add a bot to help add friendly reminders on PRs and issues. Using the same config as we have for graphql-java.

Add stale bot

---

build.gradle
gradle.properties

A while back we removed SLF4J from GraphQL Java. https://github.com/graphql-java/graphql-java/pull/3403/files Apart from the difficult PII/UGC problems, it was also causing unusual version clashes for users.
I spotted we still had SLF4J mentioned in this repo, but we don't seem to use it at all. Let's remove it to keep the set of dependencies to a minimum

Removing unused slf4j references

---

src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/DataLoaderValueCacheTest.java
src/test/java/org/dataloader/fixtures/TestKit.java
src/test/java/org/dataloader/fixtures/parameterized/ListDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/MappedDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/MappedPublisherDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/PublisherDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactories.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactory.java
src/test/java/org/dataloader/registries/ScheduledDataLoaderRegistryTest.java

We parameterise:
- `DataLoaderValueCacheTest`
- `ScheduledDataLoaderRegistryTest`
to provide increased coverage across all DataLoader implementations.
Notably, `DataLoaderValueCacheTest` is _not_ parameterised across the Publisher DataLoaders (yet) as these do not appear to work when a `ValueCache` is provided (which is what prompted this pull request). It will be fixed in a future pull request, at which point we will restore coverage.

Parameterise more tests across DataLoader implementations

---

src/main/java/org/dataloader/DataLoaderHelper.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/DataLoaderValueCacheTest.java
src/test/java/org/dataloader/fixtures/TestKit.java
src/test/java/org/dataloader/fixtures/parameterized/ListDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/MappedDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/MappedPublisherDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/PublisherDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactories.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactory.java
src/test/java/org/dataloader/registries/ScheduledDataLoaderRegistryTest.java

We resolve two bugs in the interaction between Publisher `DataLoader`s and `ValueCache`s:
- if the value was cached, we complete the corresponding queued futures immediately.
- if the value was _not_ cached, we remember to provide the queued future to the invoker so that the future can eventually be completed.
This is intended to be merged following #171, as this pull request builds of this.

Allow ValueCache to work with Publisher DataLoader

---

src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderFactory.java
src/test/java/org/dataloader/DataLoaderBuilderTest.java

This adds support for a builder pattern in DataLoaders
The idea is so we can "transform" and existing dataloader and change its values
```
DataLoader<String, Object> dataLoader2 = dataLoader1.transform(it -> {
it.options(differentOptions);
it.batchLoadFunction(batchLoader2);
});
```
This PR is a setup PR to allow for "instrumentation" of DataLoaders.  The Spring team have asked for this to allow them to "time" the batch load functions etc.. and they might not have built the data loaders at request time
This PR is small pre-req to that

Transform support for DataLoaders

---

README.md
src/main/java/org/dataloader/DataLoaderFactory.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/DataLoaderOptions.java
src/main/java/org/dataloader/DataLoaderRegistry.java
src/main/java/org/dataloader/instrumentation/ChainedDataLoaderInstrumentation.java
src/main/java/org/dataloader/instrumentation/DataLoaderInstrumentation.java
src/main/java/org/dataloader/instrumentation/DataLoaderInstrumentationContext.java
src/main/java/org/dataloader/instrumentation/DataLoaderInstrumentationHelper.java
src/main/java/org/dataloader/instrumentation/SimpleDataLoaderInstrumentationContext.java
src/main/java/org/dataloader/registries/ScheduledDataLoaderRegistry.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/fixtures/Stopwatch.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactory.java
src/test/java/org/dataloader/instrumentation/CapturingInstrumentation.java
src/test/java/org/dataloader/instrumentation/CapturingInstrumentationReturnsNull.java
src/test/java/org/dataloader/instrumentation/ChainedDataLoaderInstrumentationTest.java
src/test/java/org/dataloader/instrumentation/DataLoaderInstrumentationTest.java
src/test/java/org/dataloader/instrumentation/DataLoaderRegistryInstrumentationTest.java
src/test/java/org/dataloader/instrumentation/SimpleDataLoaderInstrumentationContextTest.java

This is now complete and ready to be merged.
DataLoaderOptions is now immutable and hence some teaks t the original code had been done

Instrumentation support for dataloader

---

build.gradle
src/main/java/org/dataloader/BatchLoader.java
src/main/java/org/dataloader/BatchLoaderContextProvider.java
src/main/java/org/dataloader/BatchLoaderEnvironment.java
src/main/java/org/dataloader/BatchLoaderEnvironmentProvider.java
src/main/java/org/dataloader/BatchLoaderWithContext.java
src/main/java/org/dataloader/BatchPublisher.java
src/main/java/org/dataloader/BatchPublisherWithContext.java
src/main/java/org/dataloader/CacheKey.java
src/main/java/org/dataloader/CacheMap.java
src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderFactory.java
src/main/java/org/dataloader/DispatchResult.java
src/main/java/org/dataloader/MappedBatchLoader.java
src/main/java/org/dataloader/MappedBatchLoaderWithContext.java
src/main/java/org/dataloader/MappedBatchPublisher.java
src/main/java/org/dataloader/MappedBatchPublisherWithContext.java
src/main/java/org/dataloader/ValueCache.java
src/main/java/org/dataloader/ValueCacheOptions.java

Adds jspecify and adds a bunch of Nullmarked to public classes.

add jspecify

---

src/main/java/org/dataloader/DataLoaderOptions.java
src/test/java/org/dataloader/DataLoaderBuilderTest.java
src/test/java/org/dataloader/DataLoaderOptionsTest.java

The DataLoaderOptions were not being copied during the `transform` method

Fixed a bug that the Spring team found

---

src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/instrumentation/ChainedDataLoaderInstrumentation.java
src/main/java/org/dataloader/instrumentation/DataLoaderInstrumentation.java
src/test/java/org/dataloader/DataLoaderCacheMapTest.java
src/test/java/org/dataloader/instrumentation/CapturingInstrumentation.java
src/test/java/org/dataloader/instrumentation/CapturingInstrumentationReturnsNull.java
src/test/java/org/dataloader/instrumentation/ChainedDataLoaderInstrumentationTest.java
src/test/java/org/dataloader/instrumentation/DataLoaderInstrumentationTest.java
src/test/java/org/dataloader/instrumentation/DataLoaderRegistryInstrumentationTest.java

The Insrtrumentation calls did not cover `load` calls.  This adds that

Added a instrumentation of load calls

---

src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DelegatingDataLoader.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/DelegatingDataLoaderTest.java
src/test/java/org/dataloader/fixtures/parameterized/DelegatingDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactories.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactory.java

This allows you to more easily wrap a DataLoader.
This uses the wonderful parameterised test factories and hence ALL the current (and future) data loader tests will run with the delegation in place.
This REALLY REALLY proves the delegation works and will continue to work for new tests

Added support for a delegating data loader

---

README.md

jcenter was sunsetted a while ago. Thanks @andimarek for spotting we are still referencing this in the readme!

Remove jcenter reference after sunset

---

build.gradle

Since org.specify import is not necessarily needed at runtime, can we make it optional?

OSGI - Make org.jspecify.* imports optional

---

src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderFactory.java
src/main/java/org/dataloader/DataLoaderRegistry.java
src/main/java/org/dataloader/DelegatingDataLoader.java
src/main/java/org/dataloader/registries/ScheduledDataLoaderRegistry.java
src/test/java/org/dataloader/ClockDataLoader.java
src/test/java/org/dataloader/DataLoaderFactoryTest.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/DelegatingDataLoaderTest.java
src/test/java/org/dataloader/fixtures/TestKit.java
src/test/java/org/dataloader/instrumentation/DataLoaderRegistryInstrumentationTest.java

This adds name to a DataLoader which we should have done from the start in retrospect
This helps Instrumentation so they can report stats in terms of "names".

Breaking change - adds a name to a DataLoader 

---

README.md
src/main/java/org/dataloader/DataLoaderFactory.java
src/main/java/org/dataloader/DataLoaderOptions.java
src/test/java/ReadmeExamples.java
src/test/java/org/dataloader/DataLoaderBatchLoaderEnvironmentTest.java
src/test/java/org/dataloader/DataLoaderBuilderTest.java
src/test/java/org/dataloader/DataLoaderFactoryTest.java
src/test/java/org/dataloader/DataLoaderOptionsTest.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java
src/test/java/org/dataloader/DataLoaderStatsTest.java
src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/DataLoaderValueCacheTest.java
src/test/java/org/dataloader/DelegatingDataLoaderTest.java
src/test/java/org/dataloader/instrumentation/ChainedDataLoaderInstrumentationTest.java
src/test/java/org/dataloader/instrumentation/DataLoaderInstrumentationTest.java
src/test/java/org/dataloader/instrumentation/DataLoaderRegistryInstrumentationTest.java
src/test/java/org/dataloader/scheduler/BatchLoaderSchedulerTest.java

https://github.com/graphql-java/java-dataloader/issues/190
We changed the semantics of DataLoaderOption to be immutable but we didnt change the API signature and this led to confusion and the possibility of bugs where previously mutable calls not longer took effect
See the issue from more details
This now makes this a breaking change and will fail at compile time

Breaking change - renaming old mutable setXX methods

---

build.gradle
src/main/java/org/dataloader/BatchLoaderEnvironment.java
src/main/java/org/dataloader/DataLoader.java
src/main/java/org/dataloader/DataLoaderRegistry.java
src/test/java/org/dataloader/DataLoaderRegistryTest.java
src/test/kotlin/org/dataloader/KotlinExamples.kt

related to https://github.com/graphql-java/java-dataloader/issues/195
Putting ErrorProne / NullAway in place

Error Prone / NullAway support for JSpecify

---

src/main/java/org/dataloader/BatchLoader.java
src/main/java/org/dataloader/BatchLoaderWithContext.java
src/main/java/org/dataloader/DataLoaderHelper.java
src/main/java/org/dataloader/MappedBatchLoader.java
src/main/java/org/dataloader/MappedBatchLoaderWithContext.java
src/main/java/org/dataloader/MappedBatchPublisher.java
src/main/java/org/dataloader/MappedBatchPublisherWithContext.java
src/test/kotlin/org/dataloader/KotlinExamples.kt

This adds `V extends @Nullable Object` on the batch loader interfaces to indicate that the values can be null.

More explicit nullable annotations on BatchLoader interfaces

---

src/test/java/org/dataloader/DataLoaderTest.java
src/test/java/org/dataloader/fixtures/parameterized/DelegatingDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/ListDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/MappedDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/MappedPublisherDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/PublisherDataLoaderFactory.java
src/test/java/org/dataloader/fixtures/parameterized/TestDataLoaderFactory.java

This only adds tests - a previous PR fixed the bug but didnt add tests
Now we have some parameterised tests for the batch loaders with context

#208 to ensure tests are in place

---

build.gradle
gradle.properties

See #227
Local maven publish says
```
<dependencies>
<dependency>
<groupId>org.reactivestreams</groupId>
<artifactId>reactive-streams</artifactId>
<version>1.0.3</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>org.jspecify</groupId>
<artifactId>jspecify</artifactId>
<version>1.0.0</version>
<scope>compile</scope>
</dependency>
</dependencies>
<name>java-dataloader</name>
<description>A pure Java 11 port of Facebook Dataloader</description>
<url>https://github.com/graphql-java/java-dataloader</url>
<inceptionYear>2017</inceptionYear>
```

Kotlin stdlib should not be a pom dep
